EQUIPMENT_DEFS = {
    {
        texture = 'clothes',
        attack = 0,
        defense = 50,
        type = 'armor',
        direction = 1,
        level = 0,
        sound = 'cloth',
    }, {
        texture = 'male_head1',
        type = 'head',
        direction = 1,
        level = 0,
    }, {
        texture = 'dagger',
        attack = 50,
        type = 'weapon',
        range = 0.5,
        direction = 1,
        level = 0,
        sound = 'sword-unsheathe',
    }, {
        texture = 'shield',
        defense = 100,
        type = 'shield',
        direction = 8,
        level = 1,
        sound = 'metal-small2',
    }, {
        texture = 'greatsword',
        attack = 200,
        type = 'weapon',
        range = 1.5,
        direction = 5,
        level = 1,
        sound = 'sword-unsheathe5',
    }, {
        texture = 'leather_armor',
        defense = 75,
        type = 'armor',
        direction = 5,
        level = 1,
        sound = 'cloth-heavy',
    }, {
        texture = 'longsword',
        attack = 150,
        type = 'weapon',
        range = 1.5,
        direction = 2,
        level = 1,
        sound = 'sword-unsheathe4',
    }, {
        texture = 'rod',
        attack = 100,
        type = 'weapon',
        range = 1,
        direction = 5,
        level = 1,
        sound = 'metal-small3',
    }, {
        texture = 'shortsword',
        attack = 100,
        type = 'weapon',
        range = 1,
        direction = 1,
        level = 1,
        sound = 'sword-unsheathe2',
    }, {
        texture = 'steel_armor',
        defense = 100,
        type = 'armor',
        direction = 8,
        level = 1,
        sound = 'armor-light',
    }, {
        texture = 'buckler',
        defense = 50,
        type = 'shield',
        direction = 7,
        level = 1,
        sound = 'interface1',
    }
}