EQUIPMENT_DEFS = {
    {
        texture = 'clothes',
        attack = 0,
        defense = 50,
        type = 'armor',
        direction = 3,
        level = 0,
        sound = 'cloth',
        offsetX = -4,
        offsetY = -1.75,
    }, {
        texture = 'male_head1',
        type = 'head',
        direction = 1,
        level = 0,
        offsetX = 0,
        offsetY = 0,
    }, {
        texture = 'dagger',
        attack = 50,
        type = 'weapon',
        range = 0.5,
        direction = 5,
        level = 0,
        sound = 'sword-unsheathe',
        offsetX = -3.75,
        offsetY = -2.25,
    }, {
        texture = 'shield',
        defense = 100,
        type = 'shield',
        direction = 8,
        level = 1,
        sound = 'metal-small2',
        offsetX = -3.8,
        offsetY = -2.2,
    }, {
        texture = 'greatsword',
        attack = 200,
        type = 'weapon',
        range = 1.5,
        direction = 5,
        level = 1,
        sound = 'sword-unsheathe5',
        offsetX = -3.5,
        offsetY = -2.5,
    }, {
        texture = 'leather_armor',
        defense = 75,
        type = 'armor',
        direction = 5,
        level = 1,
        sound = 'cloth-heavy',
        offsetX = -3.875,
        offsetY = -1.875,
    }, {
        texture = 'longsword',
        attack = 150,
        type = 'weapon',
        range = 1.5,
        direction = 2,
        level = 1,
        sound = 'sword-unsheathe4',
        offsetX = -4.5,
        offsetY = -1.75,
    }, {
        texture = 'rod',
        attack = 100,
        type = 'weapon',
        range = 1,
        direction = 5,
        level = 1,
        sound = 'metal-small3',
        offsetX = -3.6,
        offsetY = -2.4,
    }, {
        texture = 'shortsword',
        attack = 100,
        type = 'weapon',
        range = 1,
        direction = 1,
        level = 1,
        sound = 'sword-unsheathe2',
        offsetX = -4.1,
        offsetY = -1.5,
    }, {
        texture = 'steel_armor',
        defense = 100,
        type = 'armor',
        direction = 8,
        level = 1,
        sound = 'armor-light',
        offsetX = -3.9,
        offsetY = -1.9,
    }, {
        texture = 'buckler',
        defense = 50,
        type = 'shield',
        direction = 7,
        level = 1,
        sound = 'interface1',
        offsetX = -4.1,
        offsetY = -2.1,
    }
}

(function ()
    for k, def in pairs(EQUIPMENT_DEFS) do
        local offsetX, offsetY = Cartesian(def.offsetX, def.offsetY)
        def.icon = love.graphics.newQuad(128 * 23 - offsetX - 12, 
            128 * (def.direction - 1) - offsetY - 12,
            24, 24, 4096, 1024)
    end
end)()